// <auto-generated />
namespace BlogCaNhan.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class swapuserusers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(swapuserusers));
        
        string IMigrationMetadata.Id
        {
            get { return "202006141411145_swap-user-users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
